---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-fence-agents-remediation-medik8s-io-v1alpha1-fenceagentsremediationtemplate
  failurePolicy: Fail
  name: mfenceagentsremediationtemplate.kb.io
  rules:
  - apiGroups:
    - fence-agents-remediation.medik8s.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - fenceagentsremediationtemplates
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-fence-agents-remediation-medik8s-io-v1alpha1-fenceagentsremediation
  failurePolicy: Fail
  name: vfenceagentsremediation.kb.io
  rules:
  - apiGroups:
    - fence-agents-remediation.medik8s.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - fenceagentsremediations
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-fence-agents-remediation-medik8s-io-v1alpha1-fenceagentsremediationtemplate
  failurePolicy: Fail
  name: vfenceagentsremediationtemplate.kb.io
  rules:
  - apiGroups:
    - fence-agents-remediation.medik8s.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - fenceagentsremediationtemplates
  sideEffects: None
